### ISSUE TITLE
Keyboard shortcut for chroma broken for OKLch

### ISSUE THREAD

**Issue by artemshitov** [ardov/huetone#7]
C + ↓↑ shortcut doesn't have enough granularity for OKLch and causes huge swings in color.

**Comment by ardov** [comment]
Should be fixed now

**Comment by shinze** [comment]
I still have the problem on Macos with a french bepo keyboard (any browser)
